# Generated by Django 5.2 on 2026-05-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='doctors',
            new_name='doctor',
        ),
    ]
