# Generated by Django 5.2 on 2026-05-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_doctors_listing_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photos_1',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photos_2',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photos_3',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photos_4',
            new_name='photo_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photos_main',
            new_name='photo_main',
        ),
    ]
